<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "px_hybrid_auth"
 *
 * Auto generated by Extension Builder 2014-09-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'HybridAuth',
    'description' => 'Adds social sign-in via HybridAuth to TYPO3-Login and -Logout. (by portrino GmbH)',
    'category' => 'plugin',
    'author' => 'André Wuttig, Georg Ringer',
    'author_email' => 'wuttig@portrino.de, typo3@ringerge.org',
    'author_company' => 'portrino GmbH',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '3.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.2-7.99.99',
        ],
        'conflicts' => [
        ],
        'suggests' => [
        ],
    ]
];
