<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "px_hybrid_auth"
 *
 * Auto generated by Extension Builder 2014-09-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'HybridAuth',
	'description' => 'Adds social sign-in via HybridAuth to TYPO3-Login and -Logout. (by portrino GmbH)',
	'category' => 'plugin',
	'author' => 'André Wuttig',
	'author_email' => 'wuttig@portrino.de',
    'author_company' => 'portrino GmbH',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.1.2',
	'constraints' => array(
		'depends' => array(
            'php' => '5.3.0-5.5.99',
            'typo3' => '6.2.0-6.2.99',
            'extbase' => '6.2.0-6.2.99',
            'fluid' => '6.2.0-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
            'px_lib' => ''
		),
	),
);