<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "px_hybrid_auth"
 *
 * Auto generated by Extension Builder 2014-09-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'HybridAuth',
	'description' => 'Adds HybridAuth to TYPO3 Login and Logout',
	'category' => 'plugin',
	'author' => 'André Wuttig',
	'author_email' => 'wuttig@portrino.de',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '3.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);